name: ${project.name}
main: nl.hauntedmc.fairperks.FairPerks
version: ${project.version}
author: HauntedMC
website: https://www.hauntedmc.nl
api-version: "1.21"
depend: [Essentials]
softdepend: [CombatLogX]

commands:
  godmacro:
    description: Zet de god macro aan of uit
    usage: /<command>
    permission: fairperks.godmacro
